import type { Metadata, Viewport } from "next";
import { Anonymous_Pro, Azeret_Mono, Commissioner, Fira_Code, Fira_Mono, Geist_Mono, IBM_Plex_Mono, Reddit_Mono, Roboto_Mono, Source_Code_Pro } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";


const mono = Roboto_Mono({
  weight: ["400", "500","700"],
  variable: "--font-mono",
  subsets: ["latin"],
})

const sans = Commissioner({
  variable: "--font-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  interactiveWidget: "resizes-content",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ sans.variable } ${ mono.variable } antialiased ${ sans.className } bg-discord-background`}
      >
        <div className="w-full min-h-screen">
          <div className="min-h-screen mx-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
